feat: Add SSL/TLS support
snakemake/snakemake-storage-plugin-irods pull request #3
Opened 2024-02-05 18:23 UTC by stsnel

This makes it possible to use the iRODS storage plugin to connect to iRODS environments that enforce use of SSL/TLS

2024-03-07 12:09 UTC, johanneskoester requested changes
Thanks a lot! Some minor things below.

2024-03-07 12:09 UTC, johanneskoester commented on snakemake_storage_plugin_irods/__init__.py
> +        default="",
```suggestion
    client_server_negotiation: Optional[str] = field(
        default=None,
```

2024-03-07 12:09 UTC, johanneskoester commented on snakemake_storage_plugin_irods/__init__.py
> +            "help": "File with trusted CA certificates in PEM format. "
```suggestion
            "help": "Path to file with trusted CA certificates in PEM format. "
```

2024-03-08 15:09 UTC, stsnel commented
Thanks! I've included the suggested changes in the commit

2024-06-13 08:58 UTC, johanneskoester approved these changes

2024-06-13 08:59 UTC, merged